### PR TITLE
fixed sketch rendering + updating tuning

### PR DESCRIPTION
**Pull request by usselman**
Fixes issues regarding cache and updating state when Tuning Panel is changed by using the SWV library.

### CODE REVIEW

**Comment by derrickhorton** [comment]
Awesome! This is great to see.

**Comment by derrickhorton** [comment]
> Awesome! This is great to see. 

Uh oh, looks like an internal server error.

**Comment by derrickhorton** [comment]
> > Awesome! This is great to see. 
> 
> Uh oh, looks like an internal server error.
> 
> 
> 
> 

Nevermind! Maybe the lastest update was just deploying. Working now!

**Comment by derrickhorton** [comment]
This is so cool!

https://github.com/pow-co/pow.co/assets/4019818/92d8f0b9-6c7e-42cb-b172-dbed64a9f975

**Comment by usselman** [comment]
@eddiewillers Thank you! I will work next on making it scale properly for mobile, it's clearly more desktop friendly atm.

**Pull request merged**
