### PR TITLE
remove token gate for Twetch Wallet

### PR DESCRIPTION
**Pull request by 1aristotelis**

### CODE REVIEW

**Review by derrickhorton — APPROVED** [review]
Thank you Guillaume!

**Review by ielvisd — APPROVED** [review]

**Comment by stevenzeiler** [comment]
Excellent.

**Review by DanielKrawisz — APPROVED** [review]
I don't understand this at all, hopefully it works!

**Review by usselman — APPROVED** [review]
I don't use Twetch Wallet so I hope this is fixed soon otherwise I cannot use the site!

**Pull request merged**
