### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by 1aristotelis**
This PR starts the refactoring of all pow.co from nextjs v12 (pages router) to nextjs 13 (app router).
We can make that transition from page router to app router progressively:
My plan is to start with pages that need dynamic opengraph tags the most (making good use of nextjs 13 `generateMetadata`). 
In this PR: 
* /calendar becomes /events 
* a new transaction detail page @ /t/[txid] (we will still use /[txid] for now because new page is not full featured yet)

Nextjs 13 also simplifies server side rendering we will fetch data on server side much more than currently

Here's what a pow.co event link will look like when shared on social media
image

Here's what a pow.co post will look like on social media
image

### CODE REVIEW

**Comment by derrickhorton** [comment]
Wow cool, this looks great!

**Review by usselman — APPROVED** [review]
Looks great 💐

**Review by derrickhorton — APPROVED** [review]
Tested, works, looks fantastic. Terrific development. This change greatly impacts link sharability. Well done!

**Comment by 1aristotelis** [comment]
fixed the "@undefined" before merging 🙈

**Pull request merged**
