### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by 1aristotelis**
Before merging to prod all wallet actions should be tested for each wallets (did not have the time to do so)

### CODE REVIEW

**Review by stevenzeiler — DISMISSED** [review]
I get stuck in a repeating loop when signing in with Handcash. If the handcash auth token is already present it should not cause a redirect to re-auth.

**Comment by stevenzeiler** [comment]
Sensilet is not yet supported for boosting and most other transaction types, so perhaps it should be hidden for now.

**Comment by stevenzeiler** [comment]
Oh I see, your currently selected wallet is highlighted when you click "Select Wallet".

**Review by stevenzeiler — APPROVED** [review]
👍 Thank you!

**Comment by derrickhorton** [comment]
Here are the results of my review (performed today over the last 40 minutes):

PR 194 Tests:

	Relay:

		Post URL:	No
		Boost Post: 	Yes (takes 26 seconds)
		BitChat:	No

	Twetch:

		Post URL:	No
		Boost Post:	Yes (takes 15 seconds)
		BitChat:	No

	HandCash:

		Post URL:	No
		Boost Post:	Yes (takes 30 seconds)
		BitChat:	Yes

	Sensilet:

		Post URL:	No
		Boost Post:	No
		Personal Int:	No
		BitChat:	No

	Local Wallet:

		Post URL:	No
		Boost Post:	No
		BitChat: 	No

**Review by stevenzeiler — CHANGES_REQUESTED** [review]
This pull request introduces too many breaking concepts, such as a crash when you click on the profile icon of a Handcash or LocalWallet user.

The settings page should clearly show information about which wallets are connected and which are available. Overall this pull request oversimplifies the settings page and we lose too much information.

**Review by derrickhorton — APPROVED** [review]
Second Battery of Tests:

	Relay:

		Post URL:	Yes (03 seconds)
		Boost Post: 	Yes (03 seconds)
		BitChat:	Yes (11 seconds)

	Twetch:

		Post URL:	Yes (10 seconds)
		Boost Post:	Yes (01 seconds)
		BitChat:	Yes (01 seconds)

	HandCash:

		Post URL:	No  (45 seconds, Error)
				Yes (10 seconds)
		Boost Post:	Yes (30 seconds)
		BitChat:	Yes (05 seconds)

	Sensilet:

		Post URL:	No
		Boost Post:	No
		Personal Int:	Yes (00 seconds)
		BitChat:	No

	Local Wallet:

		Post URL:	No
		Boost Post:	No
		BitChat: 	No

**Comment by 1aristotelis** [comment]
I don't think we know how to handle Handcash Auth error: on my local branch i don't have an Handcash App id set, so I end up in this screen :
image

When I go back to the settings page the handcash wallet is selected as if it was successfully signed in with handcash but it's not 
image

Makes me think what happens for a regular user if he fails to authenticate with handcash, do we have a handcash error hook or something ?

**Comment by derrickhorton** [comment]
The settings page above looks great! It shows the user what wallet he has selected. 

Good thinking about handling the situation where the user gracefully fails to authenticate with HandCash.

**Review by stevenzeiler — APPROVED** [review]

**Pull request merged**
