### PR TITLE
Boost and Post with Handcash / Abstract Wallet

### PR DESCRIPTION
**Pull request by stevenzeiler**
Creates an abstract class Wallet and subclasses for each of:

- relayx
- twetch
- handcash
- sensilet
- local

The interface to the wallet requires strongly typed objects from boostpow-js and bsv.Transaction.Output

### CODE REVIEW

**Review by 1aristotelis — CHANGES_REQUESTED** [review]
image
There is definitely something wrong with the tags

**Comment by stevenzeiler** [comment]
Oh okay I see thanks for pointing that out.

**Review by 1aristotelis — APPROVED** [review]
image
Looks ok now.

**Comment by 1aristotelis** [comment]
I approve the merge but it is now urgent to get the wallet UI up to date. The settings page looks confusing AF.
image

There is one issue that can be annoying: 
You actually have to select Handcash from the dropdown list for it to be correctly connected to pow.co. 
Hitting the 'connect handcash' does'nt log the user properly
image
image
versus with dropdown list handcash option
image

**Comment by stevenzeiler** [comment]
Should Handcash become auto-selected after signing in?

**Comment by 1aristotelis** [comment]
imagine it's the first time you use the app. When you hit the connect wallet button, you would expect to be able to use the app straight after (without having to manually tell the app that this is the wallet you want to use).
Should be fixed by my commit.

**Comment by derrickhorton** [comment]
Great !

**Review by derrickhorton — APPROVED** [review]
Tested connect with HandCash, works




Tested post bitchat from HandCash, works.

Tested multiboost with HandCash, works.



PR approved! 

Many thanks for this great User Experience improvement!

**Pull request merged**
