### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by stevenzeiler**
Please approve if next.pow.co is worth of promotion to pow.co

This pull request requires 3 approvals.

### CODE REVIEW

**Comment by usselman** [comment]
I can see my tooltip when running locally from the latest version but it doesn't seem to show up on https://next.pow.co, as shown here:

Screenshot 2023-04-23 at 11 40 54 AM

Otherwise I thought that the next.pow.co experience felt slower than pow.co but after running through a few performance tests, the results are inconclusive. next.pow.co may load slower sometimes, but not always, so I imagine this is just regular variance. 
next.pow.co:
Screenshot 2023-04-23 at 11 51 11 AM
pow.co:
Screenshot 2023-04-23 at 11 52 04 AM

Given this I personally see no reason to delay on this merge as any issues can be resolved from the master branch.

**Review by usselman — APPROVED** [review]

**Comment by GuiDeMa** [comment]
There are a few things I want to see fixed before merging to main branch:
* i think there is something wrong with tagging in the more recent versions of the bootspow-button component: it tags in reverse
image
* next.pow.co/twetch is still not working (next.pow.co/api/v1/twetch is still 404)
* search for SLictionary words does not work (might be due to some cors policy on their end, we will need to fetch data server side. Would need to open next.pow.co/api/v1/slictionary API route)

**Review by 1aristotelis — CHANGES_REQUESTED** [review]
There are a few things I want to see fixed before merging to main branch:

* i think there is something wrong with tagging in the more recent versions of the bootspow-button component: it tags in reverse
image
* next.pow.co/twetch is still not working (next.pow.co/api/v1/twetch is still 404)
* search for SLictionary words does not work (might be due to some cors policy on their end, we will need to fetch data server side. Would need to open next.pow.co/api/v1/slictionary API route)
* the multi-days feed ranking data should only contain data boosted in the last 24h (it has too much data right now)
* we might want to fix the chat while we're at it

**Review by DanielKrawisz — APPROVED** [review]

**Review by DanielKrawisz — CHANGES_REQUESTED** [review]
pow.co/meet/powco-development doesn't work on brave browser. 

Edit--strange, it seems to work now. Maybe it just loaded slowly? I'm not sure what happened.

**Review by ielvisd — APPROVED** [review]
Looks good, I agree with @GuiDeMa's review but otherwise the PR looks good to me.

**Review by DanielKrawisz — APPROVED** [review]

**Comment by 1aristotelis** [comment]
The boost tag are reversed due to the fact we no longer use the boostpow api to construct jobs but the boostpow-js library since I introduced the Boost Identity protocol. I don't know how this was solved back in the days shall i simply reverse the boost tag hex string? 
https://github.com/pow-co/boostpow-button/blob/06c0cf63a6f8e3de22aa5c3bb92a8d92e5f31a92/src/SuperBoostPopup.tsx#L266

**Review by 1aristotelis — APPROVED** [review]
ok LGTM

**Pull request merged**
