### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by stevenzeiler**

### CODE REVIEW

**Review by derrickhorton — APPROVED** [review]
Nice

**Review by usselman — COMMENTED** [review]
Considering I want to make consistent small, incremental improvements to the Galaxy sketch, I wonder if it should be excluded from production until it's in some kind of more final state. I like where it is now, and it's usable, but it's basic, so I will leave the approvals to other team members.

**Review by 1aristotelis — APPROVED** [review]

**Comment by 1aristotelis** [comment]
I aggree that unfinished features (such as the galaxy page) should not be promoted to prod. However in that case it is not really an issue since there is no navlinks to pow.co/galaxy you have to willingly access that page. This is why I am enclined to approve anyway.
For future experimental features, it is better to leave them in their own branch until completed, then merge them in to `develop` then `master`

**Comment by stevenzeiler** [comment]
I think all experimental features should be promoted to prod as quickly as possible, either being a "feature flag" that can be enabled in the settings page, or at a route that cannot be directly accessed via any public links.

**Review by 1aristotelis — APPROVED** [review]

**Review by usselman — APPROVED** [review]
I'm content with where it stands right now so I'll approve to production.
- mobile experience needs to be better though

**Pull request merged**
