### PR TITLE
Display an NFT card if a Relayx market link is shared 

### PR DESCRIPTION
**Pull request by ielvisd**
Screenshot 2023-02-22 at 10 56 42 AM

Fetches NFT market data if a RelayX Market link is shared to `pow.co`. Example above. 

Improvements include general card cleanup and data presentation & being able to play the media (if any) directly in the card. If we already have a component that does this let me know @GuiDeMa, @owenkellogg. It would also be nice to be able to buy the first floor item from this card.

### CODE REVIEW

**Comment by ielvisd** [comment]
I will fix the TypeScript errors 👀

**Comment by ielvisd** [comment]
TypeScript and merge conflicts fixed @GuiDeMa, @owenkellogg

**Comment by 1aristotelis** [comment]
Awesome work man I'll merge this when i get back from work

**Comment by stevenzeiler** [comment]
+1 for buying the floor item

**Comment by usselman** [comment]
@ielvisd not sure if this is working yet, I've been trying it with a few relay market links and getting errors after pressing enter into the content field.

**Comment by usselman** [comment]
Actually seems to work sometimes, just inconsistent.

**Pull request merged**
