### PR TITLE
Sketches

### PR DESCRIPTION
**Pull request by usselman**
Creates new page at `/visualizer` that visualizes topics, using `/components/visualizer/<sketches>` and p5-react library. 
- works best when tuning panel is set to Last Week
- WIP

Screenshot 2023-06-16 at 6 29 25 AM

### CODE REVIEW

**Comment by usselman** [comment]
- removed rotating to make it cleaner
Screenshot 2023-06-16 at 6 39 11 AM

**Review by stevenzeiler — APPROVED** [review]
Excellent

**Comment by derrickhorton** [comment]
@usselman I wonder what you think about this?

It says the CircleCI test failed to build this in a docker container. 

Screenshot 2023-06-16 at 14 22 38

**Comment by usselman** [comment]
> @usselman I wonder what you think about this?
> 
> It says the CircleCI test failed to build this in a docker container.
> 
> Screenshot 2023-06-16 at 14 22 38

Should be resolved now by explicitly casting `tag` to `tag: Ranking`

**Pull request merged**
