### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by 1aristotelis**

### CODE REVIEW

**Review by derrickhorton — APPROVED** [review]
Cool Issues tab and Events tab. Tested on next.pow.co -- works!

**Comment by 1aristotelis** [comment]
I did a some refactoring for event/issues creation, can you test those as well ? I am afk for a few hours

**Comment by stevenzeiler** [comment]
https://next.pow.co/calendar says "Error, something happened"

**Comment by stevenzeiler** [comment]
Nevermind that was an issue with an API update, which is now complete. I created a calendar event and then boosted it, and expect the event to appear once boosted.

**Comment by 1aristotelis** [comment]
https://next.pow.co now has correct OpenGraph tags! 
I would advise to merge current pr as is

**Comment by derrickhorton** [comment]
Screenshot 2023-09-06 at 13 21 21

OpenGraph tags work!

**Comment by 1aristotelis** [comment]
So.. at the moment these tags are not dynamic.
I would like to use the `metadata` feature of Next13 but for that we will need to migrate to the App Router (instead of the Pages router)
https://nextjs.org/docs/app/building-your-application/upgrading/app-router-migration

**Review by stevenzeiler — APPROVED** [review]

**Pull request merged**
